export const WEATHER_FETCH_PENDING = 'WEATHER_FETCH_PENDING';

export const WEATHER_FETCH_SUCCESS = 'WEATHER_FETCH_SUCCESS';
export const FORECAST_FETCH_SUCCESS = 'FORECAST_FETCH_SUCCESS';

export const WEATHER_FETCH_ERROR = 'WEATHER_FETCH_ERROR';

export const SET_CITY = 'SET_CITY'